Support JetBrains IDEs 2024.1
bazelbuild/intellij pull request #5960
Opened 2024-01-18 19:47 UTC by tpasternak

# Checklist

- [ ] I have filed an issue about this change and discussed potential changes with the maintainers.
- [ ] I have received the approval from the maintainers to make this change.
- [ ] This is not a stylistic, refactoring, or cleanup change.

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked. See 
the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more 
details.

# Discussion thread for this change

Issue number: `<please reference the issue number or url here>`

# Description of this change

most of the files are just copies, you can compare them with:
```
diff -r sdkcompat/v2{33,41}
diff -r cpp/sdkcompat/v2{33,41}
diff -r testing/testcompat/v2{33,41}
diff intellij_platform_sdk/BUILD.idea2{33,41}
diff intellij_platform_sdk/BUILD.ue2{33,41}
diff intellij_platform_sdk/BUILD.clion2{33,41}
```

2024-01-19 18:29 UTC, ahmedyarub commented
> @ujohnny i'm getting this for clion, if something comes to your mind rn, then plase share, otherwise I'll do it myself
> 
> ```
> ERROR: clwb/BUILD:58:13: Building clwb/libclwb_lib.jar (31 source files) failed: (Exit 1): java failed: error executing Javac command (from target //clwb:clwb_lib) external/remotejdk17_linux_aarch64/bin/java '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' ... (remaining 19 arguments skipped)
> clwb/src/com/google/idea/blaze/clwb/run/GoogleTestUtilAdapter.java:35: error: cannot find symbol
>     GoogleTestUtilAdapter adapter = EP_NAME.getPoint().extensions().findFirst().orElse(null);
>                                                       ^
>   symbol:   method extensions()
>   location: interface ExtensionPoint<GoogleTestUtilAdapter>
> Target //clwb:clwb_bazel_zip failed to build
> Use --verbose_failures to see the command lines of failed build steps.
> INFO: Elapsed time: 2.659s, Critical Path: 2.16s
> INFO: 4 processes: 4 internal.
> ERROR: Build did NOT complete successfully
> ```

Does this help?
https://github.com/ujohnny/intellij/commit/eb472e4a77668d5ba733925d49f18d182000fd45

2024-01-19 21:13 UTC, ahmedyarub commented on common/util/BUILD
>      ],
I think that there is a formatting problem in here. I think that you switched between tabs and spaces or something.

2024-01-22 14:53 UTC, ujohnny commented on intellij_platform_sdk/BUILD
> +        "cpu": "darwin_x86_64",  #todo how about m1?
I'm not sure if you'd like to be in blame list for this line with this PR

2024-01-22 15:03 UTC, ujohnny requested changes
some nits, also reached you privately regarding copyrights. otherwise lgtm

2024-01-22 15:03 UTC, ujohnny commented on sdkcompat/BUILD
> +        "clion-2024.1": ["//sdkcompat/v241"],
should we keep these sorted lexicographically?

2024-01-22 15:03 UTC, ujohnny commented on third_party/go/BUILD
> +
nit: whitespace

2024-01-22 15:03 UTC, ujohnny commented on java/BUILD
> +        "@error_prone_annotations//jar"
please add trailing comma

2024-01-22 15:03 UTC, ujohnny commented on intellij_platform_sdk/build_defs.bzl
> +    "clion-2024.1": struct(
same comment re lexicographic order

2024-01-23 02:06 UTC, mai93 reviewed
thanks @tpasternak. Left minor comments

2024-01-23 12:16 UTC, ujohnny approved these changes

2024-01-23 17:45 UTC, mai93 commented on intellij_platform_sdk/BUILD.clion241
> +java_library(name = "jsr305")  # not bundled
here it is marked as unmarked, so should we link it?

2024-01-23 21:02 UTC, mai93 commented on intellij_platform_sdk/BUILD.clion241
> +java_library(name = "jsr305")  # not bundled
SGTM

2024-01-23 22:03 UTC, mai93 approved these changes

2024-01-23 22:42 UTC, merged