feat: create "Add package" EditorNotificationPanel if derive_targets_from_directories is on
bazelbuild/intellij pull request #6388
Opened 2024-04-11 14:23 UTC by tpasternak

Based on #6359 by @dkashyn-sfdc
# Checklist

- [ ] I have filed an issue about this change and discussed potential changes with the maintainers.
- [ ] I have received the approval from the maintainers to make this change.
- [ ] This is not a stylistic, refactoring, or cleanup change.

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked. See 
the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more 
details.

# Discussion thread for this change

Issue number: `<please reference the issue number or url here>`

# Description of this change

2024-04-11 14:26 UTC, tpasternak commented
The code contains some code duplications, but otherwise it would require either to put some `if` statements in the middle of the bodies, or to rework the whole file, which we would like to avoid @ujohnny @LeFrosch

2024-04-18 13:36 UTC, ujohnny commented
So initially there was a notification 

```
Do you want to add this file to your project sources?           Add file to project
```

And with this change it in some cases looks like

```
Do you want to add this file to your project sources?           Add package to project
```

I'd consider updating notification text for the new action into something like 
```
Do you want to add this package to your project sources?  Add package to project
```

Also I checked the code on a basic example with `directories: .` and click on the notification does not do anything. I guess this has to be checked before displaying the notification

[Screencast from 2024-04-18 16-33-45.webm](https://github.com/bazelbuild/intellij/assets/759709/a62b3d92-59e2-44bb-96e0-e7e799f72c3f)

2024-04-18 13:36 UTC, ujohnny requested changes

2024-04-18 13:36 UTC, ujohnny commented on base/src/com/google/idea/blaze/base/dependencies/AddSourceToProjectHelper.java
> +    List<? extends TargetExpression> targetsToSync = targets;
This is always null

2024-04-18 13:36 UTC, ujohnny commented on base/src/com/google/idea/blaze/base/dependencies/ExternalFileProjectManagementHelper.java
> +              createPanel(
It seems to me that some regions have formatting issues. I believe the indent should be 4 spaces instead of 8.

2024-04-22 11:24 UTC, ujohnny approved these changes
lgtm, but agreed to extract duplicated constant to variable in a separate PR

2024-04-22 11:26 UTC, merged