Virtual includes fix
bazelbuild/intellij pull request #6759
Opened 2024-09-16 11:22 UTC by LeFrosch

Addresses problems with the virtual includes handler:

- Fixes absolute strip prefix
- Fallback to virtual includes for include prefix (no longer an error)
- Fallback to virtual includes if a source file is generated

Also removes the `-ibazel` support and adds integration tests.

2024-09-23 22:10 UTC, anonrig commented
Is there an ETA to this pull-request changes?

2024-09-24 08:01 UTC, ujohnny commented
> Is there an ETA to this pull-request changes?

I'll check it this week

2024-09-25 17:10 UTC, ujohnny commented
@LeFrosch I almost understand the whole change, but let's have a chat on Monday as the PR description is too concise imo. I've also noticed it does not work with bzlmod (but I believe the original code didn't work either), so maybe consider this as a next step (or improve here?)

2024-09-25 17:10 UTC, ujohnny requested changes

2024-09-30 11:37 UTC, ujohnny approved these changes

2024-10-02 06:09 UTC, merged