Adding implementation for EssentialHighlightingRestarterDisablement
bazelbuild/intellij pull request #7104
Opened 2024-12-03 15:33 UTC by sellophane

# Checklist

- [ ] I have filed an issue about this change and discussed potential changes with the maintainers.
- [ ] I have received the approval from the maintainers to make this change.
- [ ] This is not a stylistic, refactoring, or cleanup change.

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked. See 
the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more 
details.

# Discussion thread for this change

Issue number: `<please reference the issue number or url here>`

# Description of this change

2025-02-14 09:05 UTC, ujohnny requested changes

2025-02-14 09:05 UTC, ujohnny commented on sdkcompat/v243/com/google/idea/sdkcompat/querysync/EssentialHighlightingRestarterDisablementAdapter.java
> +// #api243
should be 242

2025-02-14 09:16 UTC, ujohnny commented on base/BUILD
> +        "intellij-2024.3": ["src/META-INF/blaze-base-243.xml"],
251 is missing

2025-02-17 09:34 UTC, LeFrosch requested changes

2025-02-17 09:34 UTC, LeFrosch commented on base/BUILD
>          "//common/settings",
Please do not format, this will cause AOSP merge conflicts down the line. Add just add new dependencies at the end of the list.

2025-02-17 09:35 UTC, LeFrosch commented on base/BUILD
>          "//common/settings",
You can disable auto formatting in the Plugin's settings.

2025-02-26 11:42 UTC, odisseus approved these changes

2025-04-10 15:33 UTC, sellophane commented
@ujohnny @LeFrosch I need your actions here if we want to merge this

2025-04-11 07:23 UTC, LeFrosch requested changes

2025-04-11 07:23 UTC, LeFrosch commented on base/BUILD
> +        "default": [],
This looks like maintenance burden to me. Can we solve this similar to `//clwb/src/com/google/idea/blaze/clwb/radler` and use something like `select_since` instead of introducing all these xml files.

2025-06-16 12:49 UTC, LeFrosch commented
If this is ijwb only, can we move it to ijwb?

2025-09-18 10:17 UTC, merged